/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as UnauthenticatedCallbackImport } from './routes/_unauthenticated/callback'
import { Route as AuthenticatedOnboardingImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedLayoutImport } from './routes/_authenticated/_layout'
import { Route as UnauthenticatedAuthSignUpImport } from './routes/_unauthenticated/auth.sign-up'
import { Route as UnauthenticatedAuthSignInImport } from './routes/_unauthenticated/auth.sign-in'
import { Route as AuthenticatedLayoutDashboardImport } from './routes/_authenticated/_layout.dashboard'
import { Route as AuthenticatedLayoutDocumentDocIdImport } from './routes/_authenticated/_layout.document.$docId'
import { Route as AuthenticatedLayoutChannelChannelIdImport } from './routes/_authenticated/_layout.channel.$channelId'
import { Route as ApiMcpAgentUserIdCallbackSessionIdImport } from './routes/api.mcp.agent.$userId.callback.$sessionId'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const UnauthenticatedCallbackRoute = UnauthenticatedCallbackImport.update({
  id: '/_unauthenticated/callback',
  path: '/callback',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedOnboardingRoute = AuthenticatedOnboardingImport.update({
  id: '/_authenticated/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedLayoutRoute = AuthenticatedLayoutImport.update({
  id: '/_authenticated/_layout',
  getParentRoute: () => rootRoute,
} as any)

const UnauthenticatedAuthSignUpRoute = UnauthenticatedAuthSignUpImport.update({
  id: '/_unauthenticated/auth/sign-up',
  path: '/auth/sign-up',
  getParentRoute: () => rootRoute,
} as any)

const UnauthenticatedAuthSignInRoute = UnauthenticatedAuthSignInImport.update({
  id: '/_unauthenticated/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedLayoutDashboardRoute =
  AuthenticatedLayoutDashboardImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedLayoutRoute,
  } as any)

const AuthenticatedLayoutDocumentDocIdRoute =
  AuthenticatedLayoutDocumentDocIdImport.update({
    id: '/document/$docId',
    path: '/document/$docId',
    getParentRoute: () => AuthenticatedLayoutRoute,
  } as any)

const AuthenticatedLayoutChannelChannelIdRoute =
  AuthenticatedLayoutChannelChannelIdImport.update({
    id: '/channel/$channelId',
    path: '/channel/$channelId',
    getParentRoute: () => AuthenticatedLayoutRoute,
  } as any)

const ApiMcpAgentUserIdCallbackSessionIdRoute =
  ApiMcpAgentUserIdCallbackSessionIdImport.update({
    id: '/api/mcp/agent/$userId/callback/$sessionId',
    path: '/api/mcp/agent/$userId/callback/$sessionId',
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/_layout': {
      id: '/_authenticated/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedLayoutImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingImport
      parentRoute: typeof rootRoute
    }
    '/_unauthenticated/callback': {
      id: '/_unauthenticated/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof UnauthenticatedCallbackImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/_layout/dashboard': {
      id: '/_authenticated/_layout/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedLayoutDashboardImport
      parentRoute: typeof AuthenticatedLayoutImport
    }
    '/_unauthenticated/auth/sign-in': {
      id: '/_unauthenticated/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof UnauthenticatedAuthSignInImport
      parentRoute: typeof rootRoute
    }
    '/_unauthenticated/auth/sign-up': {
      id: '/_unauthenticated/auth/sign-up'
      path: '/auth/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof UnauthenticatedAuthSignUpImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/_layout/channel/$channelId': {
      id: '/_authenticated/_layout/channel/$channelId'
      path: '/channel/$channelId'
      fullPath: '/channel/$channelId'
      preLoaderRoute: typeof AuthenticatedLayoutChannelChannelIdImport
      parentRoute: typeof AuthenticatedLayoutImport
    }
    '/_authenticated/_layout/document/$docId': {
      id: '/_authenticated/_layout/document/$docId'
      path: '/document/$docId'
      fullPath: '/document/$docId'
      preLoaderRoute: typeof AuthenticatedLayoutDocumentDocIdImport
      parentRoute: typeof AuthenticatedLayoutImport
    }
    '/api/mcp/agent/$userId/callback/$sessionId': {
      id: '/api/mcp/agent/$userId/callback/$sessionId'
      path: '/api/mcp/agent/$userId/callback/$sessionId'
      fullPath: '/api/mcp/agent/$userId/callback/$sessionId'
      preLoaderRoute: typeof ApiMcpAgentUserIdCallbackSessionIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

interface AuthenticatedLayoutRouteChildren {
  AuthenticatedLayoutDashboardRoute: typeof AuthenticatedLayoutDashboardRoute
  AuthenticatedLayoutChannelChannelIdRoute: typeof AuthenticatedLayoutChannelChannelIdRoute
  AuthenticatedLayoutDocumentDocIdRoute: typeof AuthenticatedLayoutDocumentDocIdRoute
}

const AuthenticatedLayoutRouteChildren: AuthenticatedLayoutRouteChildren = {
  AuthenticatedLayoutDashboardRoute: AuthenticatedLayoutDashboardRoute,
  AuthenticatedLayoutChannelChannelIdRoute:
    AuthenticatedLayoutChannelChannelIdRoute,
  AuthenticatedLayoutDocumentDocIdRoute: AuthenticatedLayoutDocumentDocIdRoute,
}

const AuthenticatedLayoutRouteWithChildren =
  AuthenticatedLayoutRoute._addFileChildren(AuthenticatedLayoutRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof AuthenticatedLayoutRouteWithChildren
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/callback': typeof UnauthenticatedCallbackRoute
  '/dashboard': typeof AuthenticatedLayoutDashboardRoute
  '/auth/sign-in': typeof UnauthenticatedAuthSignInRoute
  '/auth/sign-up': typeof UnauthenticatedAuthSignUpRoute
  '/channel/$channelId': typeof AuthenticatedLayoutChannelChannelIdRoute
  '/document/$docId': typeof AuthenticatedLayoutDocumentDocIdRoute
  '/api/mcp/agent/$userId/callback/$sessionId': typeof ApiMcpAgentUserIdCallbackSessionIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof AuthenticatedLayoutRouteWithChildren
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/callback': typeof UnauthenticatedCallbackRoute
  '/dashboard': typeof AuthenticatedLayoutDashboardRoute
  '/auth/sign-in': typeof UnauthenticatedAuthSignInRoute
  '/auth/sign-up': typeof UnauthenticatedAuthSignUpRoute
  '/channel/$channelId': typeof AuthenticatedLayoutChannelChannelIdRoute
  '/document/$docId': typeof AuthenticatedLayoutDocumentDocIdRoute
  '/api/mcp/agent/$userId/callback/$sessionId': typeof ApiMcpAgentUserIdCallbackSessionIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_authenticated/_layout': typeof AuthenticatedLayoutRouteWithChildren
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_unauthenticated/callback': typeof UnauthenticatedCallbackRoute
  '/_authenticated/_layout/dashboard': typeof AuthenticatedLayoutDashboardRoute
  '/_unauthenticated/auth/sign-in': typeof UnauthenticatedAuthSignInRoute
  '/_unauthenticated/auth/sign-up': typeof UnauthenticatedAuthSignUpRoute
  '/_authenticated/_layout/channel/$channelId': typeof AuthenticatedLayoutChannelChannelIdRoute
  '/_authenticated/_layout/document/$docId': typeof AuthenticatedLayoutDocumentDocIdRoute
  '/api/mcp/agent/$userId/callback/$sessionId': typeof ApiMcpAgentUserIdCallbackSessionIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/onboarding'
    | '/callback'
    | '/dashboard'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/channel/$channelId'
    | '/document/$docId'
    | '/api/mcp/agent/$userId/callback/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/onboarding'
    | '/callback'
    | '/dashboard'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/channel/$channelId'
    | '/document/$docId'
    | '/api/mcp/agent/$userId/callback/$sessionId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated/_layout'
    | '/_authenticated/onboarding'
    | '/_unauthenticated/callback'
    | '/_authenticated/_layout/dashboard'
    | '/_unauthenticated/auth/sign-in'
    | '/_unauthenticated/auth/sign-up'
    | '/_authenticated/_layout/channel/$channelId'
    | '/_authenticated/_layout/document/$docId'
    | '/api/mcp/agent/$userId/callback/$sessionId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedLayoutRoute: typeof AuthenticatedLayoutRouteWithChildren
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  UnauthenticatedCallbackRoute: typeof UnauthenticatedCallbackRoute
  UnauthenticatedAuthSignInRoute: typeof UnauthenticatedAuthSignInRoute
  UnauthenticatedAuthSignUpRoute: typeof UnauthenticatedAuthSignUpRoute
  ApiMcpAgentUserIdCallbackSessionIdRoute: typeof ApiMcpAgentUserIdCallbackSessionIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedLayoutRoute: AuthenticatedLayoutRouteWithChildren,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  UnauthenticatedCallbackRoute: UnauthenticatedCallbackRoute,
  UnauthenticatedAuthSignInRoute: UnauthenticatedAuthSignInRoute,
  UnauthenticatedAuthSignUpRoute: UnauthenticatedAuthSignUpRoute,
  ApiMcpAgentUserIdCallbackSessionIdRoute:
    ApiMcpAgentUserIdCallbackSessionIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_authenticated/_layout",
        "/_authenticated/onboarding",
        "/_unauthenticated/callback",
        "/_unauthenticated/auth/sign-in",
        "/_unauthenticated/auth/sign-up",
        "/api/mcp/agent/$userId/callback/$sessionId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_authenticated/_layout": {
      "filePath": "_authenticated/_layout.tsx",
      "children": [
        "/_authenticated/_layout/dashboard",
        "/_authenticated/_layout/channel/$channelId",
        "/_authenticated/_layout/document/$docId"
      ]
    },
    "/_authenticated/onboarding": {
      "filePath": "_authenticated/onboarding.tsx"
    },
    "/_unauthenticated/callback": {
      "filePath": "_unauthenticated/callback.tsx"
    },
    "/_authenticated/_layout/dashboard": {
      "filePath": "_authenticated/_layout.dashboard.tsx",
      "parent": "/_authenticated/_layout"
    },
    "/_unauthenticated/auth/sign-in": {
      "filePath": "_unauthenticated/auth.sign-in.tsx"
    },
    "/_unauthenticated/auth/sign-up": {
      "filePath": "_unauthenticated/auth.sign-up.tsx"
    },
    "/_authenticated/_layout/channel/$channelId": {
      "filePath": "_authenticated/_layout.channel.$channelId.tsx",
      "parent": "/_authenticated/_layout"
    },
    "/_authenticated/_layout/document/$docId": {
      "filePath": "_authenticated/_layout.document.$docId.tsx",
      "parent": "/_authenticated/_layout"
    },
    "/api/mcp/agent/$userId/callback/$sessionId": {
      "filePath": "api.mcp.agent.$userId.callback.$sessionId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
